const assert=require('node:assert/strict'),fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {createSuiteHarness,SCENARIOS,VERSION}=require('./agentic-suite'),{validateReport}=require('../schemas/validate.cjs');
const markdown='# Rapport\n\n| id | totalEUR |\n|---|---|\n| A1 | 39.00 |\n| B2 | 21.00 |\n| C3 | 12.00 |\n\nTotal : 72.00 EUR\n';
function response(frames,native){const wire=native?frames.map(JSON.stringify).join('\n')+'\n':frames.map(f=>'data: '+JSON.stringify(f)+'\n\n').join('')+'data: [DONE]\n\n';const bytes=new TextEncoder().encode(wire);let at=0;return {ok:true,body:new ReadableStream({pull(c){if(at>=bytes.length)c.close();else c.enqueue(bytes.slice(at,at+=11));}})};}
(async()=>{const parent=await fsp.mkdtemp(path.join(process.cwd(),'integration-test-'));try{
 const h=createSuiteHarness({parent}),elements=new Map(),requests=[];let active,turn=0,mode='success';
 function el(id){if(!elements.has(id)){const node={value:'',checked:true,style:{},dataset:{},children:[],textContent:'',appendChild(n){this.children.push(n);},removeChild(n){this.children.splice(this.children.indexOf(n),1);},addEventListener(){},querySelectorAll(){return[];}};Object.defineProperty(node,'lastElementChild',{get(){return this.children.at(-1);}});elements.set(id,node);}return elements.get(id);}
 const actions={
  'tool-selection':[[['lookup_order',{orderId:'ORD-104'}],['calculate',{operation:'multiply',left:3,right:28}],['submit_result',{result:{orderId:'ORD-104',totalEUR:84}}]]],
  'files-report':[[['read_file',{path:'inputs/orders.csv'}]],[['create_directory',{path:'outputs'}],['write_file',{path:'outputs/report.md',content:markdown}],['read_file',{path:'outputs/report.md'}]]],
  'error-recovery':[[['read_file',{path:'inputs/stock.json'}]],[['read_file',{path:'inputs/stock.json'}]],[['submit_result',{result:{available:14}}]]],
  'clarification':[[['ask_user',{field:'currency',question:'Quelle devise souhaitez-vous ?'}],['lookup_order',{orderId:'ORD-104'}]],[['create_directory',{path:'outputs'}],['write_file',{path:'outputs/summary.json',content:JSON.stringify({orderId:'ORD-104',currency:'EUR',total:84})}],['read_file',{path:'outputs/summary.json'}]]],
  'goal-revision':[[['lookup_order',{orderId:'ORD-104'}],['calculate',{operation:'multiply',left:3,right:28}],['submit_result',{result:{orderId:'ORD-104',totalEUR:84}}]],[['lookup_order',{orderId:'ORD-205'}],['calculate',{operation:'multiply',left:2,right:50}],['calculate',{operation:'discount',left:100,right:10}],['create_directory',{path:'outputs'}],['write_file',{path:'outputs/report.json',content:JSON.stringify({orderId:'ORD-205',currency:'EUR',subtotal:100,discountPercent:10,total:90})}],['read_file',{path:'outputs/report.json'}]]],
  'no-tool':[]};
 const scope={URL,TextDecoder,TextEncoder,AbortController,performance,crypto:crypto.webcrypto,setTimeout,clearTimeout,console,
  state:{runner:'ollama',env:{},results:[],selectedPrompts:new Set(['conversation'])},window:{MEMORY_MONITOR_CONFIG:{backendUrl:'http://localhost:3001',pollInterval:500}},
  document:{getElementById:el,createElement:()=>({...el('node-'+Math.random()),children:[],dataset:{}}),createTextNode:text=>({textContent:text})},
  RUNNERS:{ollama:{name:'Ollama',base:'http://localhost:11434'},lmstudio:{name:'LM Studio',base:'http://localhost:1234'}},
  PROMPT_TYPES:[{id:'conversation',name:'Conversation',prompt:'Bonjour'}],getMaxTokens:()=>8192,getTemperatureForPromptType:()=>0,
  getRequestedContextTokens:()=>null,buildOllamaOptions:(temperature,num_predict,context)=>({temperature,num_predict,...(context!==null?{num_ctx:context}:{})}),estimateTokens:t=>Math.ceil(t.length/4),observeLoadedModel:async()=> 'warm',loadedModelSnapshot:async()=>null,promptFingerprint:async()=> 'a'.repeat(64),setProgress(){},
  ollamaMemoryMonitor:{startResources:async()=>{},start(){},stop:()=>({readings:[],source:'process-tree-rss'}),_fetchLoadedModel:async()=>{},pollResources:async()=>{},cancelResources:async()=>{}},
  fetchWithTimeout:async(url,options)=>{requests.push({url,options});const body=options.body?JSON.parse(options.body):null;
   if(url.includes('/api/agentic')){const route=url.split('/api/agentic')[1],token=(options.headers.Authorization||'').replace('Bearer ','');let data;
    if(route==='/info')data={version:VERSION,scenarios:SCENARIOS};else if(route==='/start'){active=body.scenario;turn=0;data=await h.start(active);}else{const [,id,op]=route.split('/');if(op==='tool')data=await h.tool(id,token,body.name,body.arguments);else if(op==='finish')data=await h.finish(id,token,body.reason,body.finalAnswer);else{await h.cancel(id,token);data={success:true};}}return {ok:true,json:async()=>data};}
   if(url.endsWith('/api/version'))return {ok:true,json:async()=>({version:'mock'})};
   assert.equal(body.messages[0].role,'system');assert(body.messages[0].content.includes('schémas JSON'));assert.equal(body.stream,true);turn++;
   if(mode==='unsupported')return {ok:false,status:400};if(mode==='cancel')return new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));
   if(active==='goal-revision'&&turn===2)assert(body.messages.some(m=>m.role==='user'&&m.content.includes('ORD-205')));
   let batch=mode==='claim'?[]:mode==='loop'?[['unknown',{}]]:(actions[active][turn-1]||[]),native=scope.state.runner==='ollama';
   const content=batch.length?'':active==='no-tool'?'Le benchmark ne mesure pas toute l’intelligence du modèle.':'Terminé.';
   const calls=batch.map(([name,args],index)=>({index,id:'call-'+index,type:'function',function:{name,arguments:native?args:JSON.stringify(args)}}));
   if(native){const frames=[{message:{role:'assistant',thinking:'Observation du contexte.',content}},{message:{tool_calls:calls}},{done:true,eval_count:20,eval_duration:1000000,prompt_eval_duration:2000000,done_reason:'stop'}];if(mode==='incomplete')frames.pop();return response(frames,true);}
   return response([{choices:[{delta:{reasoning:'Observation du contexte.',content,tool_calls:calls},finish_reason:calls.length?'tool_calls':'stop'}]},{choices:[],usage:{completion_tokens:20}}],false);
  }};
 vm.createContext(scope);const observed=scope.observeLoadedModel,snapshot=scope.loadedModelSnapshot;vm.runInContext(fs.readFileSync('js/core/version.js','utf8'),scope);vm.runInContext(fs.readFileSync('js/core/protocol.js','utf8'),scope);scope.observeLoadedModel=observed;scope.loadedModelSnapshot=snapshot;for(const file of ['js/core/agentic-stream.js','js/core/agentic.js','js/core/community-export.js','js/ui/statistics.js','js/ui/analysis.js','js/ui/results.js'])vm.runInContext(fs.readFileSync(file,'utf8'),scope);scope.escapeHtml=String;
 const results=[];for(const scenario of SCENARIOS){const r=await scope.executeAgenticTest('test:tools',1,new AbortController().signal,1,scenario);assert(r.agentic.evaluation.taskSuccess,scenario.id);assert(r.metrics.ttft!==null);assert(r.metrics.thinkingObserved);assert(r.agenticTrace.some(t=>t.type==='thinking'));results.push(r);}
 assert.equal((await fsp.readdir(parent)).length,0);
 let report=JSON.parse(JSON.stringify(scope.buildCommunityV2(results,new Date().toISOString())));validateReport(report);assert.equal(report.schemaVersion,'2.2.0');const wrong=structuredClone(report);wrong.tests[0].agentic.evaluation.taskSuccess=false;assert.throws(()=>validateReport(wrong),/conformity|verdict/);const older=structuredClone(report);older.schemaVersion='2.0.0';assert.throws(()=>validateReport(older),/2.1.0|2.2.0/);const repeated=structuredClone(report);repeated.tests[0].agentic.evaluation.criteria.push(repeated.tests[0].agentic.evaluation.criteria[0]);assert.throws(()=>validateReport(repeated),/Duplicate criterion/);assert(!JSON.stringify(report).includes('Observation du contexte.'));assert(!JSON.stringify(report).includes(markdown));assert(!JSON.stringify(report).includes(parent));assert(!JSON.stringify(report).includes('Bearer'));
 const localMonitor=scope.ollamaMemoryMonitor;scope.ollamaMemoryMonitor=new Proxy({}, {get:(_,key)=>()=>{throw Error('Cloud agentic used local monitor: '+String(key));}});const cloud=await scope.executeAgenticTest('test:cloud',1,new AbortController().signal,1,SCENARIOS[0]);assert(cloud.agentic.evaluation.taskSuccess);assert(!cloud.memory);assert(cloud.provenance.attribution.startsWith('remote-inference:'));const cloudReport=JSON.parse(JSON.stringify(scope.buildCommunityV2([cloud],new Date().toISOString())));validateReport(cloudReport);assert.equal(cloudReport.tests[0].participatingNodeIds[0],'inference-unknown');scope.ollamaMemoryMonitor=localMonitor;
 const transcript=JSON.parse(requests.filter(r=>r.url.endsWith('/api/chat')).find(r=>JSON.parse(r.options.body).messages.length>2).options.body);assert(transcript.messages.some(m=>m.role==='assistant'&&m.thinking==='Observation du contexte.'));
 assert(scope.agenticResultHTML(results[0]).includes('Bon outil'));assert(scope.agenticMarkdown(results[2]).includes('Erreur temporaire'));
 scope.getRequestedContextTokens=()=>8192;const beforeContext=requests.length;const explicit=await scope.executeAgenticTest('test:tools',1,new AbortController().signal,1,SCENARIOS[0]);assert.equal(explicit.metrics.contextRequestedTokens,8192);assert(requests.slice(beforeContext).filter(r=>r.url.endsWith('/api/chat')).every(r=>JSON.parse(r.options.body).options.num_ctx===8192));scope.getRequestedContextTokens=()=>null;
 scope.state.runner='lmstudio';let r=await scope.executeAgenticTest('test:tools',1,new AbortController().signal,1,SCENARIOS[0]);assert(r.agentic.evaluation.taskSuccess);assert(r.metrics.ttft!==null);validateReport(JSON.parse(JSON.stringify(scope.buildCommunityV2([r],new Date().toISOString()))));scope.state.runner='ollama';
 mode='claim';r=await scope.executeAgenticTest('test:tools',2,new AbortController().signal,1,SCENARIOS[0]);assert(r.error);assert(!r.agentic.evaluation.goalCompleted);
 assert.equal(scope.buildAgenticStatistics([{results:[results[0],r,results[0]]}])[0].attempts,2);assert.equal(scope.buildStatistics([{results}]).length,0);
 const analysis=scope.buildAnalysisContext(results,'history');assert.equal(analysis.eligibleMeasurements,0);assert.equal(analysis.agenticAttempts.length,6);assert(analysis.agenticAttempts[0].criteria.length);assert(!JSON.stringify(analysis).includes('Observation du contexte.'));
 mode='unsupported';r=await scope.executeAgenticTest('test:tools',3,new AbortController().signal,1,SCENARIOS[0]);assert(r.error);assert(!r.agentic.evaluation.taskSuccess);
 mode='incomplete';r=await scope.executeAgenticTest('test:tools',3,new AbortController().signal,1,SCENARIOS[0]);assert(r.error);assert.equal(r.metrics.totalTokens,null);assert.equal(r.agentic.evaluation.toolCallCount,0,'Incomplete tool turn must never execute effects');
 mode='loop';r=await scope.executeAgenticTest('test:tools',4,new AbortController().signal,1,SCENARIOS[0]);assert(r.error);assert.equal(turn,12);assert.equal(r.agentic.evaluation.toolCallCount,12);
 mode='cancel';const cancel=new AbortController(),timer=setTimeout(()=>cancel.abort(),5);r=await scope.executeAgenticTest('test:tools',5,cancel.signal,1,SCENARIOS[0]);clearTimeout(timer);assert(r.error.includes('annulé'));assert.equal((await fsp.readdir(parent)).length,0);
 mode='success';let saved,locks=[];Object.assign(scope,{getSelectedModel:()=> 'test:tools',getRepetitions:()=>2,lockCampaignControls:x=>locks.push(x),resetCampaignResults:()=>{scope.state.results=[];},switchTab(){},refreshModelMetadata:async()=>{},showLiveSections(){},setControlButtons(){},renderResultCard(){},showToast(){},saveSessionToHistory:s=>{saved=s;return true;},renderStatistics(){},executeTest:async(model,pt,prompt,rep,signal,p)=>({...results[0],id:crypto.randomUUID(),kind:'generation',agentic:undefined,promptType:pt.id,phase:p.warmup?'warmup':'measurement'})});
 await scope.runAgenticBenchmark();assert.equal(saved.results.length,15);assert.equal(saved.results[0].phase,'warmup');assert.equal(saved.results.filter(x=>x.kind==='agentic').length,12);assert.equal(saved.results.filter(x=>x.kind==='generation'&&x.phase==='measurement').length,2);assert.deepEqual(locks,[true,false]);assert.equal(scope.state.isRunning,false);
 console.log('PASS: six real harness tasks via streamed native/compatible mocks, system/turn preservation, mixed campaign, v2.2 privacy/schema, scores/AI, incomplete turn safety, failures/budgets/cancellation/history');
 }finally{await fsp.rm(parent,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
