const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const ctx=vm.createContext({crypto,Date,Map,Set,URL});for(const file of ['js/core/catalogue-naming.js','js/core/version.js','js/core/community-export.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const n=ctx.CatalogueNaming;
assert.equal(n.model('gemma4:12b-mlx',{parameterCount:12e9,quantization:'nvfp4'}).normalizedName,'Gemma4_12B_MLX_NVFP4');
assert.equal(n.model('gemma4:12b',{parameterCount:12e9,format:'gguf',quantization:'Q4_K_M'}).normalizedName,'Gemma4_12B_GGUF_Q4_K_M');
assert.equal(n.model('qwen3.8-flash-next',{parameterCount:125e9,format:'mlx'}).principalName,'Qwen3.8FlashNext_125B');
assert.equal(n.model('gemma4:12b',{}).principalName,'Gemma4_TailleInconnue');
assert.equal(n.model('gemma4:12b',{parameterCount:11.8e9,parameterSize:'12B'}).principalName,'Gemma4_12B');
assert.equal(n.model('qwen3.8:35b-a3b',{parameterCount:35e9,activeParameterCount:3e9,parameterSize:'3B',type:'moe'}).principalName,'Qwen3.8_35B');
assert.notEqual(n.model('hf.co/alice/gemma4-distill',{parameterCount:12e9}).normalizedName,n.model('hf.co/bob/gemma4-distill',{parameterCount:12e9}).normalizedName);
assert.notEqual(n.model('qwen3.8-27b-distill',{parameterCount:27e9}).normalizedName,n.model('qwen3.8:27b',{parameterCount:27e9}).normalizedName);
assert.notEqual(n.model('my-fine-tune',{baseName:'gemma4',parameterCount:12e9}).normalizedName,n.model('gemma4',{baseName:'gemma4',parameterCount:12e9}).normalizedName);
assert.equal(n.model('https://host/path?token=SECRET',{}).sourceRepository,null);
assert.equal(n.model('gemma4',{sourceRevision:'SECRET?'}).sourceRevision,null);
const apple={platform:'apple-silicon',cpus:[{model:'Apple M3 Pro',physicalCores:12}],gpus:[{computeUnits:18}],memory:{physicalCapacity:{value:36*2**30}}};
assert.equal(n.hardware(apple).normalizedName,'Apple_M3Pro_36Go_12CPU_18GPU');assert.equal(n.hardware(apple).provisional,true);
assert.equal(n.hardware({platform:'pc',gpus:[{model:'NVIDIA GeForce RTX 4060',capacity:{value:8*2**30}}]}).normalizedName,'RTX4060_8Go');
assert.equal(n.hardware({platform:'pc',gpus:[1,2].map(()=>({model:'RTX 4090',capacity:{value:24*2**30}}))}).normalizedName,'MultiGPU_2xRTX4090_24GoChacune');
assert.equal(n.hardware({},'Anthropic').normalizedName,'Cloud_Anthropic');
assert(!n.hardware({...apple,gpus:[{model:'Apple M3 Pro'}]}).normalizedName.includes('18GPU'));
assert(!n.hardware({platform:'pc',gpus:[{model:'RTX4060',capacity:{value:null}}]}).normalizedName.includes('Go'));
const fixture=JSON.parse(fs.readFileSync('schemas/examples/apple-generation.json')),env={hardwareInventory:{machine:fixture.machines[0]}};
const result={id:'test-1',model:'gemma4:12b-mlx',runner:'Ollama',timestamp:'2026-10-07T15:00:00Z',env,metrics:{},modelMetadata:{parameterCount:12e9,quantization:'NVFP4',format:'safetensors'}};
const legacy=ctx.buildCommunityV2([result],result.timestamp),normalized=ctx.buildNormalizedCommunity([result],result.timestamp);
const {validateReport}=require('../schemas/validate.cjs');validateReport(legacy);assert(!legacy.tests[0].model.naming);assert(!legacy.tests[0].model.format);assert.equal(normalized.schemaVersion,'2.3.0');assert.equal(normalized.tests[0].model.id,result.model);assert.equal(normalized.tests[0].model.naming.normalizedName,'Gemma4_12B_MLX_NVFP4');
const contract=JSON.parse(fs.readFileSync('schemas/community-normalized.schema.json'));validateReport(normalized,contract);
assert.throws(()=>validateReport(normalized));assert.equal(result.model,'gemma4:12b-mlx');assert(!result.naming);
const bad=structuredClone(normalized);bad.tests[0].model.naming.secret='SECRET';assert.throws(()=>validateReport(bad,contract));
const cloud=ctx.buildNormalizedCommunity([{...result,id:'remote',model:'gemma4:cloud',provenance:{attribution:'remote-inference: cloud',inferenceEndpoint:'loopback',capturedAt:result.timestamp}}],result.timestamp);assert.equal(cloud.machines.find(m=>m.id==='inference-unknown').naming.normalizedName,'Cloud_OllamaCloud');assert.equal(normalized.machines[0].naming.category,'Apple');
const remote=ctx.buildNormalizedCommunity([{...result,id:'remote',provenance:{attribution:'configured-endpoint',inferenceEndpoint:'remote',capturedAt:result.timestamp}}],result.timestamp);assert.equal(remote.machines.find(m=>m.id==='inference-unknown').naming.normalizedName,'Cloud_Ollama');
const bundle=ctx.buildNormalizedCommunity([result,{...result,id:'two',runner:'MLX LM'}],result.timestamp);assert.equal(bundle.schemaVersion,'1.1.0');for(const r of bundle.reports)validateReport(r,contract);
require('../schemas/validate-normalized.cjs').validateNormalizedReport(bundle);
assert(ctx.normalizedCommunityFilename([result,{...result,model:'another/model'}],new Date(result.timestamp)).includes('-et-1-autres-modeles-'));
assert(!ctx.normalizedCommunityFilename([result],new Date(result.timestamp)).includes('/'));

console.log('PASS: normalization, unknowns, declared total parameters, distinct sources, GPU capacities, Apple provisional/cloud, compatible default and normalized contracts');
