const assert=require('node:assert/strict'),express=require('express'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {openStore,mountDatabaseRoutes}=require('./database');
(async()=>{const dir=fs.mkdtempSync(path.join(process.cwd(),'db-ui-test-')),db=openStore(dir),app=express();mountDatabaseRoutes(app,{store:db});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 let offline=false;const local=new Map([['history',JSON.stringify([{model:'legacy',runner:'ollama',results:[{id:'old',model:'legacy'}]}])]]),toasts=[];
 const scope={crypto:crypto.webcrypto,AbortController,setTimeout,clearTimeout,console,state:{},HISTORY_KEY:'history',window:{MEMORY_MONITOR_CONFIG:{backendUrl:base}},document:{getElementById:()=>({textContent:''})},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},storedLegacyProfiles:()=>[],loadHistory(){},renderCampaignProfiles(){},renderStatistics(){},showToast:(...a)=>toasts.push(a),fetch:async(...a)=>{if(offline)throw new Error('offline');return fetch(...a);}};
 vm.createContext(scope);for(const p of ['js/core/database.js','js/core/history.js'])vm.runInContext(fs.readFileSync(p,'utf8'),scope);scope.loadHistory=()=>{};
 try{
 await scope.initializeDatabase();assert(scope.databaseView.ready);assert.equal(scope.databaseHistory().length,1);assert(local.has('history'));await scope.initializeDatabase();assert.equal(db.list('session').length,1);
 const session={model:'new',runner:'ollama',results:[{id:'p1',model:'new',metrics:{tokensPerSec:10},provenance:{applicationVersion:'0.14.0'}}]};
 const first=scope.saveSessionToHistory(session);session.results.push({id:'p2',model:'new',metrics:{tokensPerSec:12}});const second=scope.saveSessionToHistory(session);assert(await first);assert(await second);assert.equal(db.list('session').find(s=>s.model==='new').results.length,2);assert.equal(db.list('session').filter(s=>s.model==='new').length,1);
 db.patch('session',session.id,{excludedResultIds:['p1']});await scope.refreshDatabase();assert.equal(scope.databaseHistory().find(s=>s.id===session.id).results.length,1);assert.equal(db.list('session').find(s=>s.id===session.id).results.length,2);
 offline=true;session.results.push({id:'p3',model:'new'});assert.equal(await scope.saveSessionToHistory(session),false);assert(scope.state.unsavedSession);assert.equal(db.list('session').find(s=>s.id===session.id).results.length,2);offline=false;assert(await scope.saveSessionToHistory(session));assert.equal(scope.state.unsavedSession,null);
 local.clear();scope.databaseView.sessions=[];await scope.initializeDatabase();assert.equal(scope.databaseHistory().length,2,'Clearing browser data cannot erase SQLite');
 local.set('history','invalid');await scope.initializeDatabase();assert(scope.databaseView.ready,'Bad legacy data must not hide existing database');assert.equal(scope.databaseHistory().length,2);
 assert(toasts.some(t=>String(t[0]).includes('non sauvegardée')));console.log('PASS: frontend migration/copy preservation, serialized pass checkpoints, persistent exclusions, offline failure/retry, cache deletion independence, malformed legacy isolation');
 }finally{await new Promise(r=>server.close(r));db.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
