// Managed local runners: fixed recipes, no client-supplied executable/URL/shell.
const os=require('node:os'),fs=require('node:fs/promises'),path=require('node:path');
const {execFile,spawn}=require('node:child_process'),{promisify}=require('node:util');
const {randomUUID,randomBytes,createHash}=require('node:crypto');
const {localOrigin}=require('./local-exports');
const IDS=['ollama','llamacpp','mlx'];
const PORTS={ollama:11434,llamacpp:8080,mlx:8081};
const LLAMA={version:'b11429',url:'https://github.com/ggml-org/llama.cpp/releases/download/b11429/llama-b11429-bin-macos-arm64.tar.gz',sha256:'740288ec6887be94280a5dfa25b5e23a78285cab104519e6c7e218904ee82459'};
const defaultRun=async(file,args,options={})=>(await promisify(execFile)(file,args,{timeout:180000,maxBuffer:1024*1024,windowsHide:true,...options})).stdout;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function defaultFind(name){try{const value=(await defaultRun('/usr/bin/which',[name],{timeout:3000})).trim();return path.isAbsolute(value)?value:null;}catch{return null;}}
function createRunnerManager({system=os,io=fs,run=defaultRun,launch=spawn,find=defaultFind,request=fetch,nap=delay,root=path.join(os.homedir(),'Library','Application Support','LLM Benchmarker','runners')}={}){
 const processes=new Map(),plans=new Map(),jobs=new Map();let busy=false,active=null;
 const supported=()=>system.platform()==='darwin'&&system.arch()==='arm64';
 async function exists(p){try{await io.access(p);return true;}catch{return false;}}
 async function python(minor=9,native=false){const candidates=[await find('python3'),'/opt/homebrew/bin/python3','/usr/local/bin/python3','/usr/bin/python3'];for(const p of [...new Set(candidates.filter(Boolean))])try{if(p==='/usr/bin/python3'&&system.platform()==='darwin')await run('/usr/bin/xcode-select',['-p'],{timeout:3000});if(await exists(p)&&String(await run(p,['-c',`import sys, platform; print(int(sys.version_info >= (3, ${minor})${native?" and platform.machine() == 'arm64'":""}))`],{timeout:5000})).trim()==='1')return p;}catch{}return null;}
 async function binary(id){
  if(id==='ollama'){for(const app of ['/Applications/Ollama.app',path.join(system.homedir(),'Applications','Ollama.app'),path.join(root,'ollama','Ollama.app')])if(await exists(path.join(app,'Contents','Resources','ollama')))return {file:path.join(app,'Contents','Resources','ollama'),app};const file=await find('ollama');return file?{file}:null;}
  if(id==='mlx'){for(const p of [path.join(root,'mlx','bin','python3'),await python(10,true)].filter(Boolean))try{if(await exists(p)&&String(await run(p,['-c',"import importlib.util; print(int(importlib.util.find_spec('mlx_lm') is not None))"],{timeout:5000})).trim()==='1')return {file:p};}catch{}return null;}
  try{const marker=JSON.parse(await io.readFile(path.join(root,'llamacpp','installation.json'),'utf8'));if(typeof marker.binary==='string'&&!marker.binary.split('/').includes('..')&&!path.isAbsolute(marker.binary)){const file=path.join(root,'llamacpp',marker.binary),real=await io.realpath(file);if(real.startsWith(path.join(root,'llamacpp')+path.sep)&&await exists(file))return {file,version:marker.version};}}catch{}
  const file=await find('llama-server');return file?{file}:null;
 }
 async function probe(id){
  let endpoint='http://127.0.0.1:'+PORTS[id];
  if(id==='mlx'&&!processes.has(id))try{const pids=String(await run('/usr/sbin/lsof',['-nP','-iTCP:8080','-sTCP:LISTEN','-Fp'],{timeout:3000})).split('\n').filter(p=>/^p\d+$/.test(p)).map(p=>p.slice(1)).slice(0,10);if(pids.length&&/mlx_lm\.server/.test(String(await run('/bin/ps',['-p',pids.join(','),'-o','command='],{timeout:3000}))))endpoint='http://127.0.0.1:8080';}catch{}let api='unreachable',identity='unverified',version=null;
  try{const route=id==='ollama'?'/api/version':id==='llamacpp'?'/props':'/v1/models';const response=await request(endpoint+route,{signal:AbortSignal.timeout(2500),redirect:'error'});if(response.ok){const data=await response.json();if(id==='ollama'&&typeof data.version==='string'){api='ready';identity='ollama-api-version';version=data.version.slice(0,80);}else if(id==='llamacpp'&&(data.default_generation_settings||data.build_info)){api='ready';identity='llama-props';}else if(id==='mlx'&&Array.isArray(data.data)){api='compatible';identity=processes.has(id)?'managed-mlx-process':endpoint.endsWith(':8080')?'mlx-process-at-default-port':'openai-compatible-unverified';if(processes.has(id)||endpoint.endsWith(':8080'))api='ready';}else api='other-service';}else if(response.status===503)api='loading';else api='other-service';}catch{}
  const installed=await binary(id);return {id,endpoint,api,identity,version,installed:!!installed,managed:processes.has(id),supported:supported(),observedAt:new Date().toISOString()};
 }
 async function scan(){const runners=await Promise.all(IDS.map(probe));return {supported:supported(),runners,activeJob:active,root,source:'fixed loopback APIs + known application/command/module paths; installation is not API readiness'};}
 async function safeRoot(){await io.mkdir(root,{recursive:true,mode:0o700});const st=await io.lstat(root);if(!st.isDirectory()||st.isSymbolicLink())throw Error('unsafe-runner-directory');}
 async function plan(id){if(busy)throw Error('runner-operation-busy');if(!IDS.includes(id))throw Error('runner-not-allowed');if(!supported())throw Error('apple-silicon-required');if(await binary(id))throw Error('already-installed-use-start');const py=await python(id==='mlx'?10:9,id==='mlx');if(!py)throw Error(id==='mlx'?'python-3.10-required':'python-3.9-required');await safeRoot();const stat=await io.statfs(root);if(Number(stat.bavail)*Number(stat.bsize)<4*1024**3)throw Error('four-gib-disk-required');
  let version=id==='llamacpp'?LLAMA.version:id==='ollama'?'official-current':'',source=id==='llamacpp'?LLAMA.url:id==='ollama'?'https://ollama.com/download/Ollama-darwin.zip':'https://pypi.org/project/mlx-lm/';
  if(id==='mlx'){const response=await request('https://pypi.org/pypi/mlx-lm/json',{signal:AbortSignal.timeout(10000),redirect:'error'});if(!response.ok)throw Error('package-metadata-unavailable');const data=await response.json();version=data.info?.version;if(typeof version!=='string'||!/^\d+\.\d+\.\d+(?:[a-z0-9.]+)?$/.test(version))throw Error('package-version-invalid');}
  const p={id:randomUUID(),runner:id,version,source,directory:path.join(root,id),python:py,expiresAt:Date.now()+10*60*1000};while(plans.size>=20)plans.delete(plans.keys().next().value);plans.set(p.id,p);return {...p,python:undefined,notice:'Installation dans votre espace utilisateur, sans sudo ni remplacement d’une installation existante. Téléchargement de logiciel tiers ; le modèle sera choisi et chargé séparément.'};
 }
 async function download(url,file,hash,job){const response=await request(url,{signal:AbortSignal.timeout(15*60*1000)});if(!response.ok||!response.body)throw Error('download-unavailable');const handle=await io.open(file,'wx',0o600),digest=createHash('sha256');let size=0;try{for await(const chunk of response.body){size+=chunk.length;if(size>2*1024**3)throw Error('archive-too-large');digest.update(chunk);for(let offset=0;offset<chunk.length;){const written=await handle.write(chunk,offset,chunk.length-offset);if(!written.bytesWritten)throw Error('download-write-failed');offset+=written.bytesWritten;}job.downloadedBytes=size;}}finally{await handle.close();}if(hash&&digest.digest('hex')!==hash)throw Error('archive-digest-mismatch');}
 async function findServer(dir,depth=0){if(depth>5)return null;for(const ent of await io.readdir(dir,{withFileTypes:true})){if(ent.isFile()&&ent.name==='llama-server')return path.join(dir,ent.name);if(ent.isDirectory()){const found=await findServer(path.join(dir,ent.name),depth+1);if(found)return found;}}return null;}
 function publicJob(j){return {id:j.id,runner:j.runner,action:j.action,status:j.status,phase:j.phase,error:j.error||null,downloadedBytes:j.downloadedBytes||0};}
 async function task(id,action,work){if(busy)throw Error('runner-operation-busy');busy=true;const j={id:randomUUID(),runner:id,action,status:'running',phase:'Préparation'};active=j.id;while(jobs.size>=10)jobs.delete(jobs.keys().next().value);jobs.set(j.id,j);j.completion=(async()=>{try{await work(j);j.status='completed';}catch(e){j.status='failed';j.error=/^[a-z0-9.-]+$/.test(e.message)?e.message:'operation-failed';}finally{busy=false;active=null;}})();return publicJob(j);}
 async function install(body){const p=plans.get(body.planId);if(body.accepted!==true||!p||Date.now()>p.expiresAt)throw Error('valid-accepted-plan-required');return task(p.runner,'install',async j=>{plans.delete(p.id);if(await binary(p.runner))throw Error('already-installed');await safeRoot();const space=await io.statfs(root);if(Number(space.bavail)*Number(space.bsize)<4*1024**3)throw Error('four-gib-disk-required');if(await exists(p.directory))throw Error('existing-managed-directory');const stage=await io.mkdtemp(path.join(root,'.install-'));try{
   if(p.runner==='mlx'){j.phase='Création de l’environnement Python isolé';await run(p.python,['-m','venv',path.join(stage,'package')]);j.phase='Installation de mlx-lm '+p.version+' depuis PyPI';await run(path.join(stage,'package','bin','python3'),['-m','pip','install','--disable-pip-version-check','--index-url','https://pypi.org/simple','--only-binary=:all:','mlx-lm=='+p.version],{timeout:30*60*1000,env:{PATH:process.env.PATH,HOME:system.homedir(),PIP_CONFIG_FILE:'/dev/null',PYTHONNOUSERSITE:'1'}});await run(path.join(stage,'package','bin','python3'),['-c','import mlx_lm; import mlx.core']);}
   else {const zip=p.runner==='ollama',archive=path.join(stage,zip?'runner.zip':'runner.tar.gz');j.phase='Téléchargement de '+p.runner+' '+p.version;await download(p.source,archive,zip?null:LLAMA.sha256,j);j.phase='Vérification et extraction';await run(p.python,[path.join(__dirname,'extract-runner.py'),archive,path.join(stage,'package')]);if(zip){const app=path.join(stage,'package','Ollama.app');await run('/usr/bin/codesign',['--verify','--deep','--strict',app]);await run('/usr/sbin/spctl',['--assess','--type','execute',app]);}else{const bin=await findServer(path.join(stage,'package'));if(!bin)throw Error('server-binary-missing');await run(bin,['--version'],{timeout:15000});await io.writeFile(path.join(stage,'package','installation.json'),JSON.stringify({binary:path.relative(path.join(stage,'package'),bin),version:LLAMA.version,sha256:LLAMA.sha256}),{flag:'wx',mode:0o600});}}
   await io.rename(path.join(stage,'package'),p.directory);j.phase='Installation terminée ; démarrage à demander séparément';
  }finally{await io.rm(stage,{recursive:true,force:true});}
 });}
 async function start(body){const id=body.runner;if(!IDS.includes(id))throw Error('runner-not-allowed');if(!supported())throw Error('apple-silicon-required');if(body.accepted!==true)throw Error('start-consent-required');if(id!=='ollama'&&(typeof body.model!=='string'||! /^[A-Za-z0-9][A-Za-z0-9_.-]{0,95}\/[A-Za-z0-9][A-Za-z0-9_.-]{0,159}(?::[A-Za-z0-9_.-]{1,32})?$/.test(body.model)||body.model.includes('..')||id==='mlx'&&body.model.includes(':')))throw Error('huggingface-model-id-required');
  return task(id,'start',async j=>{const observed=await probe(id);if(observed.api!=='unreachable')throw Error('port-already-responding');if(processes.has(id))throw Error('managed-process-already-running');await safeRoot();const b=await binary(id);if(!b)throw Error('runner-not-installed');const args=id==='ollama'?['serve']:id==='mlx'?['-m','mlx_lm.server','--host','127.0.0.1','--port','8081','--model',body.model,'--allowed-origins','http://localhost:8001,http://127.0.0.1:8001']:['--host','127.0.0.1','--port','8080','-hf',body.model];
   const env=Object.fromEntries(['PATH','TMPDIR','LANG','LC_ALL','HF_HOME'].filter(k=>process.env[k]!==undefined).map(k=>[k,process.env[k]]));env.HOME=system.homedir();if(id==='ollama'){env.OLLAMA_HOST='127.0.0.1:11434';env.OLLAMA_ORIGINS='http://localhost:8001,http://127.0.0.1:8001';if(process.env.OLLAMA_MODELS)env.OLLAMA_MODELS=process.env.OLLAMA_MODELS;}j.phase=id==='ollama'?'Démarrage de l’API Ollama':'Démarrage ; le modèle Hugging Face peut être téléchargé et chargé';
   const child=launch(b.file,args,{cwd:root,env,shell:false,stdio:['ignore','ignore','ignore']});processes.set(id,child);let failure=null;child.once('error',()=>{failure='process-start-failed';if(processes.get(id)===child)processes.delete(id);});child.once('exit',()=>{failure='process-exited';if(processes.get(id)===child)processes.delete(id);});
   for(let i=0;i<120;i++){if(failure)throw Error(failure);await nap(1000);const p=await probe(id);if(p.api==='ready'){j.phase='API locale joignable ; compatibilité modèle à vérifier au benchmark';return;}}
   j.phase='Processus toujours lancé ; chargement non confirmé. Réactualisez la détection ou arrêtez ce service.';throw Error('readiness-not-confirmed');
  });
 }
 function stop(body){const child=processes.get(body.runner);if(!child)throw Error('not-a-managed-process');child.kill('SIGTERM');return {requested:true,runner:body.runner};}
 function status(id){const j=jobs.get(id);if(!j)throw Error('job-not-found');return publicJob(j);}
 function shutdown(){for(const child of processes.values())child.kill('SIGTERM');}
 return {scan,plan,install,start,stop,status,shutdown,wait:async id=>{await jobs.get(id)?.completion;return status(id);}};
}
function mountRunnerRoutes(app,manager=createRunnerManager()){
 const token=randomBytes(32).toString('hex');const origin=(req,res,next)=>{res.set('Cache-Control','no-store');return localOrigin(req)?next():res.status(403).json({error:'local-origin-required'});};const auth=(req,res,next)=>req.headers.authorization==='Bearer '+token?next():res.status(403).json({error:'session-required'});
 app.get('/api/runners/session',origin,(_req,res)=>res.json({token,version:'1.0.0'}));app.get('/api/runners',origin,async(_req,res)=>{try{res.json(await manager.scan());}catch{res.status(503).json({error:'detection-unavailable'});}});
 for(const action of ['plan','install','start','stop'])app.post('/api/runners/'+action,origin,auth,async(req,res)=>{try{res.json(await (action==='plan'?manager.plan(req.body?.runner):manager[action](req.body||{})));}catch(e){res.status(409).json({error:e.message});}});
 app.get('/api/runners/jobs/:id',origin,auth,(req,res)=>{try{res.json(manager.status(req.params.id));}catch{res.status(404).json({error:'job-not-found'});}});return manager;
}
module.exports={createRunnerManager,mountRunnerRoutes,LLAMA};
