const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{EventEmitter}=require('node:events');
const {createRunnerManager,mountRunnerRoutes,LLAMA}=require('./local-runners');
(async()=>{
 const root=await fs.mkdtemp(path.join(process.cwd(),'.runner-test-'));try{
 let ready=new Set(),commands=[],launches=[],fetches=[];const system={platform:()=> 'darwin',arch:()=> 'arm64',homedir:()=>root};
 const run=async(file,args)=>{commands.push({file,args});if(file==='/usr/sbin/lsof')return '';if(args[0]==='-c'){if(args[1].includes('find_spec'))return file.startsWith(root)?'1':'0';return '1';}if(args[1]==='venv'){await fs.mkdir(path.join(args[2],'bin'),{recursive:true});await fs.writeFile(path.join(args[2],'bin','python3'),'fake');return '';}
 if(args[0]?.endsWith('extract-runner.py')){await fs.mkdir(path.join(args[2],'Ollama.app','Contents','Resources'),{recursive:true});await fs.writeFile(path.join(args[2],'Ollama.app','Contents','Resources','ollama'),'fake');}return '';};
 const request=async(url)=>{fetches.push(url);if(url==='https://pypi.org/pypi/mlx-lm/json')return Response.json({info:{version:'0.31.3'}});if(url==='https://ollama.com/download/Ollama-darwin.zip')return new Response('fake signed zip');if(url===LLAMA.url)return new Response('bad digest');const id=url.includes(':11434')?'ollama':url.includes(':8081')?'mlx':'llamacpp';if(!ready.has(id))throw Error('unreachable');return Response.json(id==='ollama'?{version:'1.0'}:id==='mlx'?{data:[]}:{build_info:'llama'});};
 const launch=(file,args,options)=>{const id=args[0]==='serve'?'ollama':args[0]==='-m'?'mlx':'llamacpp',child=new EventEmitter();launches.push({file,args,options,id});ready.add(id);child.kill=signal=>{child.signal=signal;ready.delete(id);child.emit('exit',0);};return child;};
 const manager=createRunnerManager({system,root,run,request,launch,find:async name=>name==='python3'?'/usr/bin/python3':null,nap:async()=>{}});
 const initial=await manager.scan();assert(initial.runners.every(r=>!r.installed&&r.api==='unreachable'));assert.equal(fetches.filter(x=>x.startsWith('http:')).length,3);
 await assert.rejects(manager.plan('https://evil'),/not-allowed/);await assert.rejects(manager.install({accepted:true,planId:'fake'}),/valid-accepted/);const plan=await manager.plan('ollama');assert.equal(plan.source,'https://ollama.com/download/Ollama-darwin.zip');assert.equal(plan.python,undefined);await assert.rejects(manager.install({planId:plan.id,accepted:false}),/valid-accepted/);
 const installation=await manager.install({planId:plan.id,accepted:true});await assert.rejects(manager.install({planId:plan.id,accepted:true}),/busy|valid-accepted/);assert.equal((await manager.wait(installation.id)).status,'completed');assert(commands.some(x=>x.file==='/usr/bin/codesign'));assert(commands.some(x=>x.file==='/usr/sbin/spctl'));assert((await manager.scan()).runners.find(r=>r.id==='ollama').installed);await assert.rejects(manager.plan('ollama'),/already-installed/);
 const start=await manager.start({runner:'ollama',accepted:true});assert.equal((await manager.wait(start.id)).status,'completed');assert.deepEqual(launches[0].args,['serve']);assert.equal(launches[0].options.env.OLLAMA_HOST,'127.0.0.1:11434');assert.equal(launches[0].options.shell,false);assert(!('LLAMA_ARG_TOOLS' in launches[0].options.env));assert(!('PYTHONPATH' in launches[0].options.env));const occupied=await manager.start({runner:'ollama',accepted:true});assert.equal((await manager.wait(occupied.id)).error,'port-already-responding');manager.stop({runner:'ollama'});assert(!ready.has('ollama'));assert.throws(()=>manager.stop({runner:'ollama'}),/not-a-managed/);
 const mlxPlan=await manager.plan('mlx');const mj=await manager.install({planId:mlxPlan.id,accepted:true});assert.equal((await manager.wait(mj.id)).status,'completed');const pip=commands.find(x=>x.args.includes('pip'));assert(pip.args.includes('--only-binary=:all:'));assert(pip.args.includes('mlx-lm==0.31.3'));assert(!commands.some(x=>x.args.includes('--trust-remote-code')));
 for(const model of ['--host evil','https://evil','../repo/model','repo/../bad','repo/model:tag'])await assert.rejects(manager.start({runner:'mlx',accepted:true,model}),/model-id/);
 const mlxStart=await manager.start({runner:'mlx',accepted:true,model:'mlx-community/test-model'});assert.equal((await manager.wait(mlxStart.id)).status,'completed');assert(launches[1].args.includes('8081'));assert(launches[1].args.includes('127.0.0.1'));assert(!launches[1].args.includes('--trust-remote-code'));manager.shutdown();assert(!ready.has('mlx'));
 const llamaPlan=await manager.plan('llamacpp');const lj=await manager.install({planId:llamaPlan.id,accepted:true});assert.equal((await manager.wait(lj.id)).error,'archive-digest-mismatch');assert.equal(await fs.access(path.join(root,'llamacpp')).then(()=>true,()=>false),false);
 const other=createRunnerManager({system:{...system,platform:()=> 'linux'},root,run,request,find:async()=>null});await assert.rejects(other.plan('mlx'),/apple-silicon/);
 const routes=new Map(),app={get:(p,...f)=>routes.set('GET '+p,f),post:(p,...f)=>routes.set('POST '+p,f)};mountRunnerRoutes(app,manager);
 async function invoke(route,overrides={}){let code=200,result;const res={set(){return this;},status(c){code=c;return this;},json(x){result=x;return this;}};const req={socket:{remoteAddress:'127.0.0.1'},headers:{host:'localhost:3001',origin:'http://localhost:8001'},body:{runner:'mlx'},params:{},...overrides};let n=0;async function next(){const f=routes.get(route)[n++];if(f)await f(req,res,next);}await next();return {code,result};}
 const session=await invoke('GET /api/runners/session');assert.equal(session.result.token.length,64);assert.equal((await invoke('POST /api/runners/start')).code,403);assert.equal((await invoke('GET /api/runners',{headers:{host:'localhost:3001',origin:'https://remote.test'}})).code,403);assert.equal((await invoke('GET /api/runners',{socket:{remoteAddress:'192.168.1.1'}})).code,403);
 console.log('PASS: passive probes, explicit plans/consent, per-user recipes, venv/wheels, signed-app checks, fixed loopback launches, occupied ports, model validation, managed-only stop, SHA-256 rejection, concurrency and origin/token guards');
 }finally{await fs.rm(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
