const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
(async()=>{
 const html=fs.readFileSync('llm-benchmarker.html','utf8'),els=new Map();for(const m of html.matchAll(/id="([^"]+)"/g))els.set(m[1],{hidden:false,disabled:false,value:'',checked:false,textContent:'',open:false});const el=id=>els.get(id);
 const grid=html.slice(html.indexOf('id="runnerGrid"'),html.indexOf('id="localRunnerStatus"'));assert(grid.includes("selectRunner('mlx')"));assert(!grid.includes("selectRunner('openai')"));assert(html.includes('id="remoteProviders"'));assert(html.includes("selectRunner('lmstudio')"));
 let installed=false,ready=false,active=null,status='running',calls=[],refreshes=0;const s={console,state:{runner:'ollama'},RUNNERS:{ollama:{name:'Ollama',type:'local'},mlx:{name:'MLX',type:'local'},llamacpp:{name:'llama.cpp',type:'local'},openai:{name:'OpenAI',type:'api'}},document:{getElementById:el,querySelectorAll:()=>[]},setTimeout:()=>1,clearTimeout:()=>{},lockCampaignControls:()=>{},renderInterfaceMode:()=>{},exportBackendBase:()=> 'http://localhost:3001',fetchModels:async()=>refreshes++,fetchWithTimeout:async(url,opts)=>{calls.push({url,opts});let data;if(url.endsWith('/session'))data={token:'T',version:'1.0.0'};else if(url.endsWith('/api/runners'))data={supported:true,activeJob:active,runners:[{id:'ollama',api:ready?'ready':'unreachable',installed,managed:ready},{id:'mlx',api:'unreachable',installed:false,endpoint:'http://127.0.0.1:8081'},{id:'llamacpp',api:'unreachable',installed:false}]};else if(url.endsWith('/plan'))data={id:'plan',runner:'ollama',version:'current',source:'https://ollama.com',directory:'/local/runners',notice:'Third party'};else if(url.endsWith('/install')||url.endsWith('/start')){active='job';data={id:'job'};}else if(url.includes('/jobs/')){data={id:'job',status,action:installed?'start':'install',phase:'Step',downloadedBytes:100};if(status==='completed'){active=null;installed=true;}}return {ok:true,json:async()=>data};}};
 vm.createContext(s);vm.runInContext(fs.readFileSync('js/ui/local-runners.js','utf8'),s);
 await s.detectLocalRunners();assert(calls.every(x=>!x.opts.method));assert(!el('runnerPlanButton').hidden);assert(el('runnerStartButton').hidden);await s.installLocalRunner();assert(!calls.some(x=>x.url.endsWith('/install')));
 await s.prepareRunnerInstallation();assert(!el('runnerInstallPlan').hidden);assert(!s.state.isRunning);assert(el('runnerInstallDetails').textContent.includes('https://ollama.com'));el('runnerInstallAccepted').checked=true;await s.installLocalRunner();assert(s.state.isRunning);assert(s.localRunnerSetup.busy);const post=calls.find(x=>x.url.endsWith('/install'));assert.equal(JSON.parse(post.opts.body).accepted,true);assert.equal(post.opts.headers.Authorization,'Bearer T');const prior=calls.length;await s.startLocalRunner();assert.equal(calls.length,prior);
 status='completed';await s.pollRunnerSetup();assert(!s.state.isRunning);assert(el('runnerPlanButton').hidden);assert(!el('runnerStartButton').hidden);assert.equal(refreshes,0);
 s.state.runner='openai';s.renderLocalRunnerSetup();assert(el('remoteProviders').open);assert(el('runnerSetup').hidden);assert(el('remoteProviderSelected').textContent.includes('OpenAI'));s.state.runner='mlx';s.renderLocalRunnerSetup();assert.equal(s.RUNNERS.mlx.base,'http://127.0.0.1:8081');
 console.log('PASS: local-first shipped controls, collapsed cloud/legacy options, passive scan, plan/consent, operation lock, installed-vs-ready distinction and source display (DOM simulated)');
})().catch(e=>{console.error(e);process.exitCode=1;});
