const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createAdvisor}=require('./model-advisor');
const G=1024**3;
class Node{constructor(tag='div'){this.tagName=tag;this.children=[];this.value='';this.checked=false;this.disabled=false;this.hidden=false;this.listeners={};this._text='';}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(n=>n.textContent||'').join('');}appendChild(n){this.children.push(n);return n;}append(...nodes){nodes.forEach(n=>this.appendChild(n));}addEventListener(k,f){this.listeners[k]=f;}}
(async()=>{
 const els=new Map(),html=fs.readFileSync('llm-benchmarker.html','utf8');for(const m of html.matchAll(/<([a-z]+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const n=new Node(m[1]);n.id=m[3];n.value=/value="([^"]*)"/.exec(m[2])?.[1]||'';n.disabled=/\bdisabled\b/.test(m[2]);els.set(n.id,n);}
 const el=id=>els.get(id);const data=await createAdvisor({system:{platform:()=> 'darwin',arch:()=> 'arm64',totalmem:()=>36*G,freemem:()=>G},io:{statfs:async()=>({bavail:1000,bsize:G})},modelsPath:'/home/test/.ollama/models'}).analyze(4096);
 let calls=[],mode='normal',activeSession=null,polls=0,refreshes=0,locks=[];const s={console,Set,state:{runner:'ollama'},document:{getElementById:el,createElement:tag=>new Node(tag),createTextNode:t=>({textContent:t}),querySelectorAll:()=>[el('advisorContext'),el('advisorAnalyze'),el('advisorDownload')]},exportBackendBase:()=> 'http://localhost:3001',showToast:()=>{},lockCampaignControls:v=>locks.push(v),renderInterfaceMode:()=>{},fetchModels:async()=>refreshes++,setTimeout:()=>123,clearTimeout:()=>{},fetchWithTimeout:async(url,opts)=>{
  calls.push({url,opts});if(url.endsWith('/session'))return {ok:true,json:async()=>({version:'1.0.0',token:'TOKEN',activeJob:activeSession})};if(url.includes('?context='))return {ok:true,json:async()=>data};if(url.endsWith('/download'))return mode==='fail'?{ok:false,json:async()=>({error:'selection-budget-insufficient'})}:{ok:true,json:async()=>({id:'job-1'})};if(url.includes('/jobs/')){polls++;return mode==='lost'?{ok:false,json:async()=>({error:'job-not-found'})}:{ok:true,json:async()=>({status:mode==='complete'?'completed':'running',entries:[{model:'mistral:7b',status:'downloading',message:'pulling',layerTotal:10,layerCompleted:5}]})};}throw Error(url);}};
 vm.createContext(s);vm.runInContext(fs.readFileSync('js/ui/model-advisor.js','utf8'),s);await s.openModelAdvisor();assert.equal(el('modelAdvisorModal').hidden,false);assert.equal(el('advisorVariants').children.length,data.variants.length);assert(el('advisorHardware').textContent.includes('/home/test/.ollama/models'));
 el('advisorFamily').value='minimax-m3';s.renderModelAdvisor();assert.equal(el('advisorVariants').children.length,1);assert(el('advisorVariants').textContent.includes('Cloud uniquement'));assert(el('advisorVariants').children[0].children[0].children[0].disabled);
 el('advisorFamily').value='mistral';s.renderModelAdvisor();const checkbox=el('advisorVariants').children[0].children[0].children[0];checkbox.checked=true;checkbox.listeners.change();assert.equal(s.modelAdvisor.selected.size,1);assert(el('advisorDownload').disabled);el('advisorPathConfirmed').checked=true;s.updateAdvisorSelection();assert.equal(el('advisorDownload').disabled,false);
 el('advisorContext').value='8192';s.updateAdvisorSelection();assert(el('advisorDownload').disabled);assert(el('advisorSelection').textContent.includes('recalculez'));await s.downloadAdvisedModels();assert(!calls.some(x=>x.url.endsWith('/download')));
 el('advisorContext').value='4096';s.updateAdvisorSelection();await s.downloadAdvisedModels();assert(s.state.isRunning);assert(s.modelAdvisor.downloading);assert.equal(polls,1);const post=calls.find(x=>x.url.endsWith('/download'));assert.equal(post.opts.headers.Authorization,'Bearer TOKEN');assert.deepEqual(JSON.parse(post.opts.body).models,['mistral:7b']);assert.equal(JSON.parse(post.opts.body).contextTokens,4096);assert(el('advisorJobs').textContent.includes('couche 50 %'));assert(!el('advisorCancel').disabled);
 const before=calls.length;await s.downloadAdvisedModels();assert.equal(calls.length,before);s.closeModelAdvisor();assert(el('modelAdvisorModal').hidden);assert(s.modelAdvisor.downloading);
 mode='complete';await s.pollAdvisorJob();assert(!s.state.isRunning);assert(!s.modelAdvisor.downloading);assert.equal(refreshes,1);assert.deepEqual(locks,[true,true,false]);
 mode='fail';await s.downloadAdvisedModels();assert(!s.state.isRunning);assert(el('advisorMessage').textContent.includes('non confirmé'));activeSession='job-1';await s.downloadAdvisedModels();assert(s.modelAdvisor.downloading);activeSession=null;mode='complete';await s.pollAdvisorJob();mode='normal';await s.downloadAdvisedModels();mode='lost';await s.pollAdvisorJob();assert(!s.modelAdvisor.downloading);assert(el('advisorMessage').textContent.includes('redémarrage'));
 // Hostile markup from metadata stays literal text; no innerHTML is used in rendering.
 data.variants[0].notes='<img src=x onerror=attack()>';el('advisorFamily').value=data.variants[0].family;s.renderModelAdvisor();assert(el('advisorVariants').textContent.includes('<img src=x onerror=attack()>'));
 console.log('PASS: catalog/filter/cloud display, explicit selection/path, stale context, busy lock, layer progress, completion, failed start, lost job and text-only rendering (DOM simulated)');
})().catch(e=>{console.error(e);process.exitCode=1;});
