const assert=require('node:assert/strict');
const {catalog,estimate,diskSnapshot,createAdvisor,mountAdvisorRoutes}=require('./model-advisor');
const G=1024**3,hw={supported:true,totalBytes:36*G,diskFreeBytes:1000*G};
const small=catalog.variants.find(v=>v.id==='mistral:7b');
const system={platform:()=> 'darwin',arch:()=> 'arm64',totalmem:()=>36*G,freemem:()=>G};
const io={statfs:async()=>({bavail:1000,bsize:G})};
function stream(lines){const text=lines.map(x=>JSON.stringify(x)).join('\n');return new Response(new ReadableStream({start(c){const b=new TextEncoder().encode(text);c.enqueue(b.slice(0,17));c.enqueue(b.slice(17));c.close();}}));}
function requests({manifestSize=small.downloadGB*1e9,lines=[{status:'pulling',total:100,completed:50},{status:'success'}],fail=false,onPull=()=>{}}={}){const calls=[];const request=async(url,options)=>{calls.push({url,options});if(url.startsWith('https://registry.ollama.ai/'))return fail?new Response('',{status:404}):Response.json({config:{size:10},layers:[{size:manifestSize}]});onPull();return stream(lines);};return {request,calls};}
(async()=>{
 const families=['qwen3.8','qwen3.6','qwen3.8-flash-next','gemma4','ornith','ornith-1.5','nemotron3','nemotron-3.5-lightning','minimax-m3','mistral-medium-3.5','mistral','mistral-nemo','mistral-small3.2'];
 assert.deepEqual([...new Set(catalog.variants.map(v=>v.family))].sort(),families.sort());assert.equal(new Set(catalog.variants.map(v=>v.id)).size,catalog.variants.length);
 for(const v of catalog.variants){assert.equal(v.id,v.family+':'+v.tag);assert.equal(v.source,'https://ollama.com/library/'+v.family);assert(['dense','moe','unknown'].includes(v.architecture));if(v.deployment==='local')assert(v.downloadGB>0);}
 assert.equal(estimate(small,hw).status,'green');assert.equal(estimate({...small,downloadGB:18},hw).status,'orange');assert.equal(estimate({...small,downloadGB:29},hw).status,'red');assert.equal(estimate({...small,downloadGB:80},hw).status,'unavailable');
 assert.equal(estimate(small,{...hw,diskFreeBytes:G}).selectable,false);assert.equal(estimate(small,{...hw,supported:false}).status,'unavailable');assert.equal(estimate(small,{...hw,totalBytes:null}).reserveBytes,null);assert.equal(estimate(small,{...hw,diskFreeBytes:null}).status,'unknown');
 assert.equal(estimate(catalog.variants.find(v=>v.deployment==='cloud'),hw).status,'cloud');assert.throws(()=>estimate(small,hw,128));
 assert.deepEqual(estimate({...small,architecture:'moe'},hw).range,estimate(small,hw).range);assert(estimate(small,hw,32768).range.upperBytes>estimate(small,hw,4096).range.upperBytes);
 let probes=[];const snap=await diskSnapshot('/data/models',{statfs:async p=>{probes.push(p);if(p==='/data/models')throw Object.assign(Error(),{code:'ENOENT'});return {bavail:99,bsize:4096};}});assert.deepEqual(probes,['/data/models','/data']);assert.equal(snap.diskFreeBytes,99*4096);assert.equal(snap.pathVerified,false);
 const mock=requests(),service=createAdvisor({system,io,request:mock.request,modelsPath:'/data/models'}),body={models:[small.id,'mistral-nemo:12b'],contextTokens:4096,pathConfirmed:true};
 const analysis=await service.analyze(4096);assert.equal(analysis.variants.length,catalog.variants.length);assert.equal(analysis.hardware.memorySource.startsWith('node:os'),true);
 await assert.rejects(service.start({...body,pathConfirmed:false}),/not-confirmed/);await assert.rejects(service.start({...body,models:['https://evil/model']}),/not-allowed/);await assert.rejects(service.start({...body,models:[small.id,small.id]}),/selection-invalid/);await assert.rejects(service.start({...body,models:['minimax-m3:cloud']}),/not-allowed/);
 const concurrent=service.start(body);await assert.rejects(service.start(body),/download-busy/);const job=await concurrent;const done=await service.wait(job.id);assert.equal(done.status,'completed');assert(done.entries.every(e=>e.status==='installed'));assert.equal(service.activeJob(),null);assert.equal(mock.calls.length,4);assert.deepEqual(mock.calls.filter(x=>x.url.startsWith('http:')).map(x=>JSON.parse(x.options.body).model),body.models);assert(mock.calls.every(x=>x.url.startsWith('https://registry.ollama.ai/v2/library/')||x.url==='http://127.0.0.1:11434/api/pull'));
 for(const [options,reason] of [[{fail:true},'manifest-unavailable'],[{manifestSize:100*G},'current-budget-insufficient'],[{lines:[{status:'pulling'}]},'pull-incomplete'],[{lines:[{error:'SECRET'}]},'ollama-pull-error']]){const m=requests(options),s=createAdvisor({system,io,request:m.request});const j=await s.start(body);const r=await s.wait(j.id);assert.equal(r.status,'failed');assert.equal(r.entries[0].message,reason);assert.equal(r.entries[1].status,'not-started');}
 const lowdisk={statfs:async()=>({bavail:1,bsize:G})};const noSpace=createAdvisor({system,io:lowdisk,request:mock.request});await assert.rejects(noSpace.start(body),/budget/);
 let space=1000;const changingDisk={statfs:async()=>({bavail:space,bsize:G})},m=requests({onPull:()=>{space=1;}}),s=createAdvisor({system,io:changingDisk,request:m.request});const j=await s.start(body);assert.equal((await s.wait(j.id)).entries[0].message,'disk-reserve-reached');
 const cancelRequest=async(url,opts)=>url.startsWith('https:')?await new Promise((resolve,reject)=>{opts.signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true});}):stream([{status:'success'}]);const cancelled=createAdvisor({system,io,request:cancelRequest});const c=await cancelled.start(body);cancelled.cancel(c.id);assert.equal((await cancelled.wait(c.id)).status,'cancelled');
 const routes=new Map(),app={get:(p,...f)=>routes.set('GET '+p,f),post:(p,...f)=>routes.set('POST '+p,f)};mountAdvisorRoutes(app,service);
 async function invoke(route,req={}){let code=200,result,headers={};const res={status(c){code=c;return this;},set(k,v){headers[k]=v;return this;},json(x){result=x;return this;}};const full={socket:{remoteAddress:'127.0.0.1'},headers:{host:'localhost:3001',origin:'http://localhost:8001'},query:{},params:{},...req};const handlers=routes.get(route);let i=0;async function next(){if(i<handlers.length)await handlers[i++](full,res,next);}await next();return {code,result,headers};}
 const session=await invoke('GET /api/models/advisor/session');assert.equal(session.headers['Cache-Control'],'no-store');assert.equal(session.result.token.length,64);
 assert.equal((await invoke('POST /api/models/advisor/download',{body})).code,403);assert.equal((await invoke('GET /api/models/advisor/session',{headers:{host:'localhost:3001',origin:'https://evil.example'}})).code,403);assert.equal((await invoke('GET /api/models/advisor/session',{socket:{remoteAddress:'192.168.1.4'}})).code,403);
 const allowed=await invoke('POST /api/models/advisor/download',{headers:{host:'localhost:3001',origin:'http://localhost:8001',authorization:'Bearer '+session.result.token},body});assert.equal(allowed.code,200);await service.wait(allowed.result.id);
 console.log('PASS: 13 families, estimator bounds/unknowns/MoE, disk volume, sequential pulls, lease, manifests, cancellation, provider failures, disk reserve and local/token guards');
})().catch(e=>{console.error(e);process.exitCode=1;});
