// Local observations and explicit setup; no install/start on load or runner selection.
var localRunnerSetup={data:null,token:null,plan:null,job:null,busy:false,timer:null};
function runnerSetupMessage(text){document.getElementById('runnerOperationStatus').textContent=text;}
function runnerSetupBusy(){return !!(state.isRunning||state.batchActive||state.analysisRunning||state.configuring);}
async function localRunnerRequest(route,body){var response=await fetchWithTimeout(exportBackendBase()+'/api/runners'+route,{...(body===undefined?{}:{method:'POST',body:JSON.stringify(body)}),headers:{'Content-Type':'application/json',...(localRunnerSetup.token?{Authorization:'Bearer '+localRunnerSetup.token}:{})}},30000);var data=await response.json();if(!response.ok)throw Error(data.error||'runner-service-unavailable');return data;}
async function detectLocalRunners(){
 if(runnerSetupBusy()&&!localRunnerSetup.busy)return;
 try{var session=await localRunnerRequest('/session');localRunnerSetup.token=session.token;localRunnerSetup.data=await localRunnerRequest('');renderLocalRunnerSetup();
  if(localRunnerSetup.data.activeJob&&!localRunnerSetup.busy){localRunnerSetup.job=localRunnerSetup.data.activeJob;lockRunnerSetup(true);pollRunnerSetup();}
 }catch(e){document.getElementById('localRunnerStatus').textContent='Détection indisponible : lancez le backend à jour (npm start).';document.getElementById('runnerSetup').hidden=true;}
}
function renderLocalRunnerSetup(){
 var remote=RUNNERS[state.runner]?.type==='api';document.getElementById('remoteProviderSelected').textContent=remote?'· '+RUNNERS[state.runner].name:'';if(remote)document.getElementById('remoteProviders').open=true;
 if(['custom','lmstudio'].includes(state.runner))document.getElementById('otherLocalRunners').open=true;
 var data=localRunnerSetup.data;if(!data)return;
 var labels={ready:'API détectée',compatible:'API compatible, moteur non confirmé',loading:'Service en chargement',unreachable:'API non joignable','other-service':'Autre service ou API protégée sur ce port'};
 document.getElementById('localRunnerStatus').textContent=data.runners.map(r=>RUNNERS[r.id].name+' : '+labels[r.api]+(r.installed?' · installé':' · installation non retrouvée')).join('\n');
 var observed=data.runners.find(r=>r.id===state.runner),panel=document.getElementById('runnerSetup');panel.hidden=!observed;if(!observed)return;
 if(observed.id==='mlx'&&['http://127.0.0.1:8080','http://127.0.0.1:8081'].includes(observed.endpoint))RUNNERS.mlx.base=observed.endpoint;
 var available=observed.api==='ready'||observed.api==='compatible',notListening=observed.api==='unreachable';
 document.getElementById('runnerSetupDescription').textContent=available?'Nous avons détecté une API locale. '+(observed.api==='compatible'?'Le moteur reste à confirmer ; aucun remplacement proposé.':'Vous pouvez choisir un modèle et lancer le benchmark.') : observed.installed?'Le runner est installé ; son API n’est pas encore joignable.':data.supported?'Runner non retrouvé : une installation gérée peut être préparée ici.':'Installation intégrée réservée à Apple Silicon dans cette version ; utilisez un service déjà installé sur les autres systèmes.';
 document.getElementById('runnerPlanButton').hidden=observed.installed||available||!notListening||!data.supported;
 document.getElementById('runnerStartButton').hidden=!observed.installed||!notListening||!data.supported;
 document.getElementById('runnerModelLabel').hidden=observed.id==='ollama'||!observed.installed||available;
 document.getElementById('runnerStartNotice').hidden=observed.id==='ollama'||!observed.installed||available;
 document.getElementById('runnerStopButton').hidden=!observed.managed;
 if(localRunnerSetup.plan?.runner!==state.runner){document.getElementById('runnerInstallPlan').hidden=true;document.getElementById('runnerInstallAccepted').checked=false;}
}
function lockRunnerSetup(locked){localRunnerSetup.busy=locked;state.isRunning=locked;lockCampaignControls(locked);document.querySelectorAll('#runnerSetup button, #runnerSetup input').forEach(el=>el.disabled=locked);if(!locked&&typeof renderInterfaceMode==='function')renderInterfaceMode();}
async function prepareRunnerInstallation(){if(runnerSetupBusy())return;lockRunnerSetup(true);try{localRunnerSetup.plan=await localRunnerRequest('/plan',{runner:state.runner});var p=localRunnerSetup.plan;document.getElementById('runnerInstallDetails').textContent=RUNNERS[p.runner].name+' · version '+p.version+' · source : '+p.source+' · destination : '+p.directory+' · '+p.notice;document.getElementById('runnerInstallAccepted').checked=false;document.getElementById('runnerInstallPlan').hidden=false;runnerSetupMessage('Vérifiez le plan puis acceptez pour installer. Aucun modèle ne sera téléchargé pendant l’installation du runner.');}catch(e){runnerSetupMessage('Installation non préparée : '+runnerSetupError(e.message));}finally{lockRunnerSetup(false);}}
function runnerSetupError(code){return {'huggingface-model-id-required':'Renseignez un identifiant Hugging Face organisation/modèle compatible ; pour llama.cpp, :quantification est facultatif.', 'valid-accepted-plan-required':'Le plan doit être accepté et encore valide ; préparez-le à nouveau si nécessaire.', 'already-installed-use-start':'Le runner est déjà installé ; utilisez le bouton de démarrage.', 'runner-not-installed':'Installez d’abord le runner ou vérifiez sa configuration existante.', 'python-3.9-required':'Python 3.9 ou supérieur est nécessaire à la vérification et à l’extraction des archives.', 'python-3.10-required':'Python 3.10 ou supérieur, natif arm64, doit être installé. Le serveur Python de la page ne garantit pas cette version.','apple-silicon-required':'Installation gérée disponible uniquement sur Apple Silicon.','four-gib-disk-required':'Au moins 4 GiB libres sont nécessaires pour préparer le runner.','port-already-responding':'Un service répond déjà sur ce port ; aucune instance supplémentaire n’a été démarrée.','readiness-not-confirmed':'Le processus est lancé, mais son API n’est pas encore prête. Réactualisez la détection ou arrêtez le service géré.','existing-managed-directory':'Le dossier géré existe déjà. Vérifiez-le avant toute nouvelle installation ; aucun écrasement effectué.','not-a-managed-process':'Ce service n’a pas été lancé par ce backend ; arrêtez-le dans son application.','operation-failed':'Une étape système a échoué (réseau, dépendances, signature ou permissions). L’installation n’est pas confirmée.','package-metadata-unavailable':'PyPI est inaccessible ; installation non préparée.','archive-digest-mismatch':'L’archive llama.cpp ne correspond pas à son SHA-256 attendu ; installation refusée.'}[code]||code;}
async function launchRunnerSetup(action,body){if(runnerSetupBusy())return;lockRunnerSetup(true);try{var job=await localRunnerRequest('/'+action,body);localRunnerSetup.job=job.id;await pollRunnerSetup();}catch(e){try{var data=await localRunnerRequest('');if(data.activeJob){localRunnerSetup.job=data.activeJob;await pollRunnerSetup();return;}}catch(_){}lockRunnerSetup(false);runnerSetupMessage('Opération non confirmée : '+runnerSetupError(e.message));}}
async function installLocalRunner(){if(!document.getElementById('runnerInstallAccepted').checked||localRunnerSetup.plan?.runner!==state.runner){runnerSetupMessage('Acceptez d’abord le plan du runner sélectionné.');return;}await launchRunnerSetup('install',{planId:localRunnerSetup.plan.id,accepted:true});}
async function startLocalRunner(){await launchRunnerSetup('start',{runner:state.runner,model:document.getElementById('runnerSetupModel').value.trim(),accepted:true});}
async function stopLocalRunner(){if(runnerSetupBusy())return;try{await localRunnerRequest('/stop',{runner:state.runner});runnerSetupMessage('Arrêt demandé au service lancé par ce backend.');await detectLocalRunners();}catch(e){runnerSetupMessage(runnerSetupError(e.message));}}
async function pollRunnerSetup(){clearTimeout(localRunnerSetup.timer);try{var job=await localRunnerRequest('/jobs/'+localRunnerSetup.job);runnerSetupMessage(job.phase+(job.downloadedBytes?' · '+(job.downloadedBytes/1024**2).toFixed(1)+' MiB téléchargés':'')+(job.error?' · '+runnerSetupError(job.error):''));if(job.status==='running'){localRunnerSetup.timer=setTimeout(pollRunnerSetup,1500);return;}lockRunnerSetup(false);localRunnerSetup.plan=null;document.getElementById('runnerInstallPlan').hidden=true;await detectLocalRunners();if(job.status==='completed'&&job.action==='start')await fetchModels();}catch(e){if(e.message==='job-not-found'){lockRunnerSetup(false);runnerSetupMessage('Suivi perdu après redémarrage du backend. Vérifiez la détection avant de relancer.');return;}runnerSetupMessage('Suivi momentanément indisponible ; l’opération peut continuer.');localRunnerSetup.timer=setTimeout(pollRunnerSetup,3000);}}
